import { Router } from 'express';
import PDFDocument from 'pdfkit';

const router = Router();

router.post('/export', async (req, res) => {
  try {
    const sessionId = typeof req.body?.sessionId === 'string' ? req.body.sessionId.trim() : '';
    const results = req.body?.results;

    if (!sessionId) {
      return res.status(400).json({ error: 'sessionId is required.' });
    }

    if (!results || typeof results !== 'object') {
      return res.status(400).json({ error: 'results payload is required.' });
    }

    const {
      ats_score = 0,
      match_percentage = 0,
      present_skills = [],
      missing_skills = [],
      suggestions = [],
    } = results;

    const doc = new PDFDocument({ margin: 50 });
    const filename = 'resume-analysis.pdf';

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);

    doc.pipe(res);

    doc.fontSize(24).text('Resume Analysis Report', { align: 'left' });
    doc.moveDown(0.4);
    doc.fontSize(11).fillColor('gray').text(`Generated: ${new Date().toLocaleString()}`);
    doc.text(`Session ID: ${sessionId}`);
    doc.moveDown(1);

    doc.fillColor('black').fontSize(14).text('ATS Score');
    doc.fontSize(36).text(`${ats_score}`);
    doc.moveDown(0.5);

    doc.fontSize(14).text(`Match Percentage: ${match_percentage}%`);
    doc.moveDown(1);

    doc.fontSize(14).text('Present Skills');
    if (present_skills.length === 0) {
      doc.fontSize(11).text('- None');
    } else {
      present_skills.forEach((skill) => doc.fontSize(11).text(`- ${skill}`));
    }
    doc.moveDown(0.8);

    doc.fontSize(14).text('Missing Skills');
    if (missing_skills.length === 0) {
      doc.fontSize(11).text('- None');
    } else {
      missing_skills.forEach((skill) => doc.fontSize(11).text(`- ${skill}`));
    }
    doc.moveDown(0.8);

    doc.fontSize(14).text('Improvement Suggestions');
    if (suggestions.length === 0) {
      doc.fontSize(11).text('1. No suggestions generated.');
    } else {
      suggestions.forEach((tip, index) => doc.fontSize(11).text(`${index + 1}. ${tip}`));
    }

    const footerY = doc.page.height - 50;
    doc.fontSize(10).fillColor('gray').text('Generated by ResumeIQ', 50, footerY, {
      align: 'center',
      width: doc.page.width - 100,
    });

    doc.end();
  } catch (err) {
    return res.status(500).json({ error: 'Failed to export PDF', message: err.message });
  }
});

export default router;
